spring.application.name=techmarket-product-service

# MongoDB
spring.data.mongodb.uri=mongodb://${MONGODB_HOST}:${MONGODB_PORT}/techmarket_products

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}

server.port=8081